id: https://osmt.wgu.edu/api/skills/440b6917-1ec0-4103-b610-6aa5f9e08f0c
status: published
uuid: 440b6917-1ec0-4103-b610-6aa5f9e08f0c
skillName: Machine Learning Algorithms Application
skillStatement: Apply machine learning algorithms
keywords:
  - Machine Learning
  - Artificial Intelligence (AI)
occupations: []
publishDate: '2023-06-01T16:29:00.098805'
archiveDate: null
category: Artificial Intelligence (AI)
